// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmLMOCbGF7WP6_zEKvpg2IQLRPHxh2ir0',
    appId: '1:33800468217:web:355ebba19a34aa9c6f9428',
    messagingSenderId: '33800468217',
    projectId: 'lapak-bantul-modify',
    authDomain: 'lapak-bantul-modify.firebaseapp.com',
    storageBucket: 'lapak-bantul-modify.firebasestorage.app',
    measurementId: 'G-SBTGYTZ5ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-KmTsmaHTQixrVys3b0zpqqOcNFuZ8k',
    appId: '1:33800468217:android:dcdeab3d38fc307d6f9428',
    messagingSenderId: '33800468217',
    projectId: 'lapak-bantul-modify',
    storageBucket: 'lapak-bantul-modify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK_0mReEWqcCXC5C24XC5vNO7zR3bdByI',
    appId: '1:33800468217:ios:718cc9fb8938dff66f9428',
    messagingSenderId: '33800468217',
    projectId: 'lapak-bantul-modify',
    storageBucket: 'lapak-bantul-modify.firebasestorage.app',
    iosClientId:
        '33800468217-btts8j0h0h3iahsiute9hm3qrmuqdb1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapakBantul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK_0mReEWqcCXC5C24XC5vNO7zR3bdByI',
    appId: '1:33800468217:ios:718cc9fb8938dff66f9428',
    messagingSenderId: '33800468217',
    projectId: 'lapak-bantul-modify',
    storageBucket: 'lapak-bantul-modify.firebasestorage.app',
    iosClientId:
        '33800468217-btts8j0h0h3iahsiute9hm3qrmuqdb1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapakBantul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmLMOCbGF7WP6_zEKvpg2IQLRPHxh2ir0',
    appId: '1:33800468217:web:fa8ed809e2d0db386f9428',
    messagingSenderId: '33800468217',
    projectId: 'lapak-bantul-modify',
    authDomain: 'lapak-bantul-modify.firebaseapp.com',
    storageBucket: 'lapak-bantul-modify.firebasestorage.app',
    measurementId: 'G-JJ5BM1ZYNV',
  );
}
